import { Beer, FoodPairing } from './beer';

//const FOOD: FoodPairing[] = [
//{ name: 'zuvis, mesa, juros gerybes' },
//];

export const BEERS: Beer[] = [
    {
        id: 1,
        name: 'Pilsner',
        sort: 'Lager',
        description: 'short beer description about this kind of beer',
        image_url: 'https://www.monde-selection.com/wp-content/uploads/2020/05/_XT211287-854x1000.png',
        food_pairing: ['meat, fish, other see food'],
        abv: 5,
        ph: 5,
    },
    {
        id: 2,
        name: 'Kriek',
        sort: 'Lager',
        description: 'short beer description',
        image_url: 'https://cdn11.bigcommerce.com/s-4dsnxp/images/stencil/500x659/products/7710/9064/Lindemans_Kriek__79667.1594279393.png?c=2',
        food_pairing: ['cheese, vegies, fried bread'],
        abv: 5,
        ph: 5,
    },
    {
        id: 3,
        name: 'Volfas Engelman',
        sort: 'Stout',
        description: 'short beer description',
        image_url: 'https://www.maistoteka.lt/wp-content/uploads/2020/11/VOLFAS-ENGELMAN-RINKTINIS-min-1.png',
        food_pairing: ['meat, fish, other see food'],
        abv: 4,
        ph: 5,
    },
    {
        id: 4,
        name: 'Heineken',
        sort: 'Stout',
        description: 'short beer description',
        image_url: 'https://www.heineken.com/media-us/01pfxdqq/heineken-original-bottle.png?quality=85',
        food_pairing: ['cheese, vegies, fried bread'],
        abv: 6,
        ph: 5,
    },
    {
        id: 5,
        name: 'Utenos Lager',
        sort: 'Lager',
        description: 'short beer description',
        image_url: 'https://i.pinimg.com/originals/6e/19/24/6e19242d9ba7337d416de0f4564a9e76.png',
        food_pairing: ['meat, fish, other see food'],
        abv: 5,
        ph: 5,
    },
    {
        id: 6,
        name: 'Hercule Stout',
        sort: 'Stout',
        description: 'short beer description',
        image_url: 'https://www.beermerchants.com/pub/media/catalog/product/cache/0c46622f88f930c2812af2e65bc76081/i/m/img_1276.png',
        food_pairing: ['cheese, vegies, fried bread'],
        abv: 2,
        ph: 5,
    },
    {
        id: 7,
        name: 'Kvietinis',
        sort: 'Elis',
        description: 'short beer description',
        image_url: 'https://shop.rinkuskiai.lt/wp-content/uploads/2020/06/Rinku%C5%A1kiai-Kvietinis.png',
        food_pairing: ['meat, fish, other see food'],
        abv: 3,
        ph: 5,
    },
    {
        id: 8,
        name: 'Kauno Tamsusis',
        sort: 'Elis',
        description: 'short beer description',
        image_url: 'https://kaunoalus.lt/wp-content/uploads/2020/07/Kauno-Tamsusis-min-1.png',
        food_pairing: ['cheese, vegies, fried bread'],
        abv: 0,
        ph: 5,
    },
];
